// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotiCore.API.Models.DataContext;

namespace NotiCore.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210208054441_SeedSources")]
    partial class SeedSources
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Authors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScrapedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArticleId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TopicId");

                    b.HasIndex("Url", "SourceId", "TopicId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            Abbreviation = "EN",
                            Description = "English",
                            IsActive = true
                        },
                        new
                        {
                            LanguageId = 2,
                            Abbreviation = "ES",
                            Description = "Spanish",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SourceId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            SourceId = 1,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "BBC UK",
                            Url = "https://www.bbc.co.uk/"
                        },
                        new
                        {
                            SourceId = 2,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "BBC US",
                            Url = "https://www.bbc.com/"
                        },
                        new
                        {
                            SourceId = 3,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Edition CNN",
                            Url = "https://www.edition.cnn.com/"
                        },
                        new
                        {
                            SourceId = 4,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "CNN",
                            Url = "https://www.cnn.com/"
                        },
                        new
                        {
                            SourceId = 5,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "NY Times",
                            Url = "https://www.nytimes.com/"
                        },
                        new
                        {
                            SourceId = 6,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Daily Mail",
                            Url = "https://www.dailymail.co.uk/"
                        },
                        new
                        {
                            SourceId = 7,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Guardian",
                            Url = "https://www.theguardian.com/"
                        },
                        new
                        {
                            SourceId = 8,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Fox News",
                            Url = "https://www.foxnews.com/"
                        },
                        new
                        {
                            SourceId = 9,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Yahoo Finance",
                            Url = "https://www.finance.yahoo.com/"
                        },
                        new
                        {
                            SourceId = 10,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Washington Post",
                            Url = "https://www.washingtonpost.com/"
                        },
                        new
                        {
                            SourceId = 11,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "CNBC",
                            Url = "https://www.cnbc.com/"
                        },
                        new
                        {
                            SourceId = 12,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Express UK",
                            Url = "https://www.express.co.uk/"
                        },
                        new
                        {
                            SourceId = 13,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "USA Today",
                            Url = "https://www.usatoday.com/"
                        },
                        new
                        {
                            SourceId = 14,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Buzzfeed",
                            Url = "https://www.buzzfeed.com/us/"
                        },
                        new
                        {
                            SourceId = 15,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "NY Post",
                            Url = "https://www.nypost.com/"
                        },
                        new
                        {
                            SourceId = 16,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Businessinsider",
                            Url = "https://www.businessinsider.com/"
                        },
                        new
                        {
                            SourceId = 17,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Forbes",
                            Url = "https://www.forbes.com/"
                        },
                        new
                        {
                            SourceId = 18,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "ABC AU",
                            Url = "https://www.abc.net.au/"
                        },
                        new
                        {
                            SourceId = 19,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Mirror UK",
                            Url = "https://www.mirror.co.uk/"
                        },
                        new
                        {
                            SourceId = 20,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "TechCrunch",
                            Url = "https://www.techcrunch.com/"
                        },
                        new
                        {
                            SourceId = 21,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Al Jazeera",
                            Url = "https://www.aljazeera.com/"
                        },
                        new
                        {
                            SourceId = 22,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Defence blog",
                            Url = "https://www.defence-blog.com/"
                        },
                        new
                        {
                            SourceId = 23,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Global Issues",
                            Url = "https://www.globalissues.org/"
                        },
                        new
                        {
                            SourceId = 24,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Cipher Brief",
                            Url = "https://www.thecipherbrief.com/"
                        },
                        new
                        {
                            SourceId = 25,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "World News Super Fast",
                            Url = "https://www.worldnewssuperfast.blogspot.com/"
                        },
                        new
                        {
                            SourceId = 26,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "RT World News",
                            Url = "https://www.rt.com/news/"
                        },
                        new
                        {
                            SourceId = 27,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "National Public Radio",
                            Url = "https://www.npr.org/"
                        },
                        new
                        {
                            SourceId = 28,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "ABC News",
                            Url = "https://www.abcnews.go.com/"
                        },
                        new
                        {
                            SourceId = 29,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "CBS",
                            Url = "https://www.cbsnews.com/"
                        },
                        new
                        {
                            SourceId = 30,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Sputnik",
                            Url = "https://www.sputniknews.com/"
                        },
                        new
                        {
                            SourceId = 31,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Independent",
                            Url = "https://www.independent.co.uk/"
                        },
                        new
                        {
                            SourceId = 32,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "CBC",
                            Url = "https://www.cbc.ca/"
                        },
                        new
                        {
                            SourceId = 33,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "LA Times",
                            Url = "https://www.latimes.com/"
                        },
                        new
                        {
                            SourceId = 34,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Time",
                            Url = "https://www.time.com/"
                        },
                        new
                        {
                            SourceId = 35,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Sun",
                            Url = "https://www.thesun.co.uk/"
                        },
                        new
                        {
                            SourceId = 36,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Euro News",
                            Url = "https://www.euronews.com/"
                        },
                        new
                        {
                            SourceId = 37,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Vox",
                            Url = "https://www.vox.com/"
                        },
                        new
                        {
                            SourceId = 38,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Seattle Times",
                            Url = "https://www.seattletimes.com/"
                        },
                        new
                        {
                            SourceId = 39,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Channel News Asia",
                            Url = "https://www.channelnewsasia.com/"
                        },
                        new
                        {
                            SourceId = 40,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Global News",
                            Url = "https://www.globalnews.ca/"
                        },
                        new
                        {
                            SourceId = 41,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Sydney Morning Herald",
                            Url = "https://www.smh.com.au/"
                        },
                        new
                        {
                            SourceId = 42,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "France 24",
                            Url = "https://www.france24.com/en/"
                        },
                        new
                        {
                            SourceId = 43,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "South China Morning Post",
                            Url = "https://www.scmp.com/"
                        },
                        new
                        {
                            SourceId = 44,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Universal",
                            Url = "https://www.eluniversal.com.mx/"
                        },
                        new
                        {
                            SourceId = 45,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Debate",
                            Url = "https://www.debate.com.mx/"
                        },
                        new
                        {
                            SourceId = 46,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Excelsior",
                            Url = "https://www.excelsior.com.mx/"
                        },
                        new
                        {
                            SourceId = 47,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Reforma",
                            Url = "https://www.reforma.com/"
                        },
                        new
                        {
                            SourceId = 48,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Vanguardia",
                            Url = "https://www.vanguardia.com.mx/"
                        },
                        new
                        {
                            SourceId = 49,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Siglo de Torreón",
                            Url = "https://www.elsiglodetorreon.com.mx/"
                        },
                        new
                        {
                            SourceId = 50,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Mexico News Daily",
                            Url = "https://www.mexiconewsdaily.com/"
                        },
                        new
                        {
                            SourceId = 51,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "La Razón",
                            Url = "https://www.razon.com.mx/"
                        },
                        new
                        {
                            SourceId = 52,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "La Jornada",
                            Url = "https://www.jornada.com.mx/"
                        },
                        new
                        {
                            SourceId = 53,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Milenio",
                            Url = "https://www.milenio.com/"
                        },
                        new
                        {
                            SourceId = 54,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Diario MX",
                            Url = "https://www.diario.mx/"
                        },
                        new
                        {
                            SourceId = 55,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Proceso",
                            Url = "https://www.proceso.com.mx/"
                        },
                        new
                        {
                            SourceId = 56,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Financiero",
                            Url = "https://www.elfinanciero.com.mx/"
                        },
                        new
                        {
                            SourceId = 57,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "SDP Noticias",
                            Url = "https://www.sdpnoticias.com/"
                        },
                        new
                        {
                            SourceId = 58,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Sin Embargo",
                            Url = "https://www.sinembargo.mx/"
                        },
                        new
                        {
                            SourceId = 59,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Publimetro",
                            Url = "https://www.publimetro.com.mx/mx/"
                        },
                        new
                        {
                            SourceId = 60,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Norte",
                            Url = "https://www.elnorte.com/"
                        },
                        new
                        {
                            SourceId = 61,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Radio Fórmula",
                            Url = "https://www.radioformula.com.mx/"
                        },
                        new
                        {
                            SourceId = 62,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Informador Jalisco",
                            Url = "https://www.informador.mx/"
                        },
                        new
                        {
                            SourceId = 63,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "24 Horas México",
                            Url = "https://www.24-horas.mx/"
                        },
                        new
                        {
                            SourceId = 64,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "El Imparcial Oaxaca",
                            Url = "https://imparcialoaxaca.mx/"
                        },
                        new
                        {
                            SourceId = 65,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Diario Basta Hidalgo",
                            Url = "https://www.diariobasta.com/"
                        },
                        new
                        {
                            SourceId = 66,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "The Yucatán Times",
                            Url = "https://www.theyucatantimes.com/"
                        },
                        new
                        {
                            SourceId = 67,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Precencia Veracruz",
                            Url = "https://www.presencia.mx/default.aspx/"
                        },
                        new
                        {
                            SourceId = 68,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Quequi",
                            Url = "https://www.quequi.com.mx/"
                        },
                        new
                        {
                            SourceId = 69,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Diario Plaza Juárez",
                            Url = "https://www.plazajuarez.mx/"
                        },
                        new
                        {
                            SourceId = 70,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "8 Columnas",
                            Url = "https://www.8columnas.com.mx/"
                        },
                        new
                        {
                            SourceId = 71,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Expreso Chiapas",
                            Url = "http://www.expresochiapas.com/"
                        },
                        new
                        {
                            SourceId = 72,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Capital Querétaro",
                            Url = "https://www.capitalqueretaro.com.mx/"
                        },
                        new
                        {
                            SourceId = 73,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Grupo Metropoli",
                            Url = "https://www.grupometropoli.net/"
                        },
                        new
                        {
                            SourceId = 74,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Novedades Campeche",
                            Url = "https://www.novedadescampeche.com.mx/"
                        },
                        new
                        {
                            SourceId = 75,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "NAI México",
                            Url = "http://www.naimexico.com/news/"
                        },
                        new
                        {
                            SourceId = 76,
                            IsActive = true,
                            LanguageId = 2,
                            Name = "Gizmodo en español",
                            Url = "https://www.es.gizmodo.com/"
                        },
                        new
                        {
                            SourceId = 77,
                            IsActive = true,
                            LanguageId = 1,
                            Name = "Gizmodo",
                            Url = "https://www.gizmodo.com/"
                        });
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.SourceSubscription", b =>
                {
                    b.Property<int>("SourceSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SubcriberId")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberId")
                        .HasColumnType("int");

                    b.HasKey("SourceSubscriptionId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("SourceSubscriptions");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Subscriber", b =>
                {
                    b.Property<int>("SubscriberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("HasAuthorized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("SubscriberId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("TopicId");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            Description = "Tech",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 2,
                            Description = "News",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 3,
                            Description = "Business",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 4,
                            Description = "Science",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 5,
                            Description = "Finance",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 6,
                            Description = "Food",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 7,
                            Description = "Politics",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 8,
                            Description = "Economics",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 9,
                            Description = "Travel",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 10,
                            Description = "Entertainment",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 11,
                            Description = "Music",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 12,
                            Description = "Sport",
                            IsActive = true
                        },
                        new
                        {
                            TopicId = 13,
                            Description = "World",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.TopicSubscription", b =>
                {
                    b.Property<int>("TopicSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("TopicSubscriptionId");

                    b.HasIndex("SubscriberId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicSubscriptions");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Article", b =>
                {
                    b.HasOne("NotiCore.API.Models.DataContext.Source", "Source")
                        .WithMany("Articles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotiCore.API.Models.DataContext.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Source", b =>
                {
                    b.HasOne("NotiCore.API.Models.DataContext.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.SourceSubscription", b =>
                {
                    b.HasOne("NotiCore.API.Models.DataContext.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotiCore.API.Models.DataContext.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId");

                    b.Navigation("Source");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.TopicSubscription", b =>
                {
                    b.HasOne("NotiCore.API.Models.DataContext.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotiCore.API.Models.DataContext.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NotiCore.API.Models.DataContext.Source", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
