// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using NotiCoreTopicML.Model;

namespace NotiCoreTopicML.Model
{
    public class ConsumeModel
    {
        private static Lazy<PredictionEngine<TopicModelInput, TopicModelOutput>> PredictionEngine = new Lazy<PredictionEngine<TopicModelInput, TopicModelOutput>>(CreatePredictionEngine);

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static TopicModelOutput Predict(TopicModelInput input)
        {
            TopicModelOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<TopicModelInput, TopicModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            string modelPath = @"";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<TopicModelInput, TopicModelOutput>(mlModel);

            return predEngine;
        }
    }
}
