// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NotiCoreTopicML.Model
{
    public class ModelInput
    {
        [ColumnName("topic"), LoadColumn(0)]
        public string Topic { get; set; }


        [ColumnName("text"), LoadColumn(1)]
        public string Text { get; set; }


    }
}
