// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NotiCoreML.Model
{
    public class ModelInput
    {
        [ColumnName("content"), LoadColumn(0)]
        public string Content { get; set; }


        [ColumnName("target"), LoadColumn(1)]
        public string Target { get; set; }


        [ColumnName("source"), LoadColumn(2)]
        public string Source { get; set; }


    }
}
